loname: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "typescript" ]
permissions:
  contents: read
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src
            package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx prettier --write .


      - run: pip install pre-commit
      - run: pre-commit run --all-files

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
